server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 168168
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /**

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.bliu.entity

shiro:
  anon: /components/**,/css/**,/font/**,/img/**,/js/**,/vender/**


